title = "ClimaPur"
baseURL = "https://climapur.ca/"
languageCode = "fr-CA"
theme = 'gohugo-theme-ananke'
resourceDir = "../resources"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
pagination.pagerSize = 0
googleAnalytics = "G-HQKJCQF52L"
enableRobotsTXT = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[imaging]
quality = 85
resampleFilter = "CatmullRom"
anchor = "Center"

[languages]
[languages.fr]
title = "ClimaPur"
description = "Services professionnels de nettoyage CVC sur la Rive-Nord de Montréal. Améliorez la qualité d'air, l'efficacité énergétique et prolongez la durée de vie de vos appareils. Estimations gratuites : 514-358-9878"
weight = 1
contentDir = "content/fr"

[languages.fr.params]
keywords = "nettoyage CVC, entretien climatiseur, Rive-Nord Montréal, nettoyage mini-split, qualité air intérieur, service CVC, entretien unité chauffage, CVC résidentiel"
[[languages.fr.menu.main]]
name = "Bienvenue"
identifier = "menu.home"
url = "/"
weight = 1

[[languages.fr.menu.main]]
name = "Nos services"
identifier = "menu.services"
url = "/services"
weight = 2

[[languages.fr.menu.main]]
name = "À propos"
identifier = "menu.about"
url = "/about"
weight = 3

[[languages.fr.menu.main]]
name = "Contact"
identifier = "menu.contact"
url = "/contact"
weight = 4

[[languages.fr.menu.main]]
name = "FAQ"
identifier = "menu.faq"
url = "/faq"
weight = 5

[languages.en]
title = "ClimaPur"
description = "Professional HVAC cleaning & maintenance services in Montreal's North Shore. Improve air quality, boost efficiency & extend your unit's lifespan. Free quotes: 514-358-9878"
weight = 2
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages

[languages.en.params]
  keywords = "HVAC cleaning, air conditioner maintenance, Montreal North Shore, ductless mini-split cleaning, indoor air quality, HVAC service, heating unit maintenance, residential HVAC" 

[[languages.en.menu.main]]
name = "Home"
identifier = "menu.home"
url = "/en"
weight = 1

[[languages.en.menu.main]]
name = "Our services"
identifier = "menu.services"
url = "/en/services"
weight = 2

[[languages.en.menu.main]]
name = "About"
identifier = "menu.about"
url = "/en/about"
weight = 3

[[languages.en.menu.main]]
name = "Contact"
identifier = "menu.contact"
url = "/en/contact"
weight = 4

[[languages.en.menu.main]]
name = "FAQ"
identifier = "menu.faq"
url = "/en/faq"
weight = 5

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "images/favicon.ico"
site_logo = "images/logoClimaPur-v2.png"
background_color_class = "bg-black"
recent_posts_number = 3
custom_css = ["custom.css", "special.css"]
defaultKeywords = ["nettoyage", "climatisation", "montreal"]
phone = "1-514-358-9878"
email = "infoclimapur@gmail.com"
