[build]
    command = "hugo --gc --minify"
    publish = "public"

[context.production.environment]
    HUGO_VERSION = "0.147.4"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

