[build]
    command = "hugo --gc --minify"
    publish = "public"

[context.production.environment]
    HUGO_VERSION = "0.147.4"

[[redirects]]
  from = "https://climapur.netlify.app/*"
  to = "https://climapur.ca/"
  status = 301
  force = true
